replicaCount: 1
clusterName: eshop-aks
pathBase: /webstatus

image:
  repository: elefebvreoncontainers/webstatuslef
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {

  }
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: HealthChecksUI__HealthChecks__0__Name
      key: name__webportal__hc
    - name: HealthChecksUI__HealthChecks__0__Uri
      key: internalurls__webportal__hc
    - name: HealthChecksUI__HealthChecks__1__Name
      key: name__webgoogle__hc
    - name: HealthChecksUI__HealthChecks__1__Uri
      key: internalurls__webgoogle__hc
    - name: HealthChecksUI__HealthChecks__2__Name
      key: name__weboffice__hc
    - name: HealthChecksUI__HealthChecks__2__Uri
      key: internalurls__weboffice__hc
    - name: HealthChecksUI__HealthChecks__3__Name
      key: name__webimap__hc
    - name: HealthChecksUI__HealthChecks__3__Uri
      key: internalurls__webimap__hc
    - name: HealthChecksUI__HealthChecks__4__Name
      key: name__weblexon__hc
    - name: HealthChecksUI__HealthChecks__4__Uri
      key: internalurls__weblexon__hc
    - name: HealthChecksUI__HealthChecks__5__Name
      key: name__accountapigw__hc
    - name: HealthChecksUI__HealthChecks__5__Uri
      key: internalurls__accountapigw__hc
    - name: HealthChecksUI__HealthChecks__6__Name
      key: name__lexonapigw__hc
    - name: HealthChecksUI__HealthChecks__6__Uri
      key: internalurls__lexonapigw__hc
    - name: HealthChecksUI__HealthChecks__7__Name
      key: name__accountapi__hc
    - name: HealthChecksUI__HealthChecks__7__Uri
      key: internalurls__accountapi__hc
    - name: HealthChecksUI__HealthChecks__8__Name
      key: name__lexonapi__hc
    - name: HealthChecksUI__HealthChecks__8__Uri
      key: internalurls__lexonapi__hc
    - name: HealthChecksUI__HealthChecks__9__Name
      key: name__lexonmysqlapi__hc
    - name: HealthChecksUI__HealthChecks__9__Uri
      key: internalurls__lexonmysqlapi__hc
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
