variables:
    registryEndpoint: lefebvre-docker
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/BuildingBlocks/*
    - src/Web/WebGoogleClient/*
    - k8s-LEF/helm/webgoogle/*            
jobs:
- template: ../buildimages.yaml
  parameters:
    services: webgoogle
    registryEndpoint: $(registryEndpoint)          
    helmfrom: $(Build.SourcesDirectory)/k8s-LEF/helm
    helmto: $(Build.ArtifactStagingDirectory)/k8s-LEF/helm      
