
{{- $name := include "webportal.fullname" . -}}
{{- $identity := include "url-of" (list .Values.app.ingress.entries.identity .) -}}
{{- $webshoppingapigw := include "url-of" (list .Values.app.ingress.entries.webshoppingapigw .) -}}
{{- $mvc := include "url-of" (list .Values.app.ingress.entries.mvc .) -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webportal.name" . }}
    chart: {{ template "webportal.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: "{{ .Values.inf.appinsights.key }}"
  all__UseAzureServiceBus: "{{ .Values.inf.eventbus.useAzure }}"
  all_EnableLoadTest: "{{ .Values.inf.misc.useLoadTest }}"
  webmvc__keystore: {{ .Values.inf.redis.keystore.constr }}
  internalurls__lexonapi: http://{{ .Values.app.svc.lexonapi }}
  internalurls__lexonmysqlapi: http://{{ .Values.app.svc.lexonmysqlapi }}
  internalurls__accountapi: http://{{ .Values.app.svc.accountapi }}/hc
  internalurls__lexonapigw: http://{{ .Values.app.svc.lexonapigw }}/hc
  internalurls__accountapigw: http://{{ .Values.app.svc.accountapigw }}/hc
  internalurls__identity__hc: http://{{ .Values.app.svc.identity }}/hc
  urls__IdentityUrl: http://{{ $identity }}  
  config.js: {{ toYaml .Values.configValues | indent 4 }}
