{{- $name := include "apigwlex.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "ocelot-{{ $name }}"
  labels:
    app: {{ template "apigwlex.name" . }}
    chart: {{ template "apigwlex.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ (.Files.Glob "configuration-lexon.json").AsConfig  | indent 2 }}

