replicaCount: 1
clusterName: eshop-aks
pathBase: /webportal

image:
  repository: elefebvreoncontainers/webportalclient
  tag: linux-lef-main-containers
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  tls: []

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:
    - name: ApplicationInsights__InstrumentationKey
      key: all__InstrumentationKey
    - name: UseLoadTest
      key: all_EnableLoadTest
    - name: LexonApiUrlHC
      key: internalurls__lexonapi
    - name: LexonMySqlApiUrlHC
      key: internalurls__lexonmysqlapi
    - name: AccountApiUrlHC
      key: internalurls__accountapi
    - name: LexonApiGatewayUrlHC
      key: internalurls__lexonapigw
    - name: AccountApiGatewayUrlHC
      key: internalurls__accountapigw
    - name: IdentityUrlHC
      key: internalurls__identity__hc      
    - name: IdentityUrl
      key: urls__IdentityUrl 
    - name: SignalrHubUrl
      key: urls__apigwws
      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: OrchestratorType
      value: 'K8S'
    - name: IsClusterEnv
      value: 'True'
      
configValues: |
  window.REACT_APP_ENVIRONMENT='PRE'
  window.API_ACCOUNTS='https://lexbox-test-apigwacc.lefebvre.es'
  window.URL_INBOX_GOOGLE= 'https://lexbox-test-webgoogle.lefebvre.es'
  window.URL_INBOX_OUTLOOK= 'https://lexbox-test-webgraph.lefebvre.es'
  window.URL_INBOX_IMAP= 'https://lexbox-test-webimap.lefebvre.es'
  window.RELEASE= 'RC 0.18'