apiVersion: v1
kind: ConfigMap
metadata:
  name: weblexonclient-config
data:
  config.js: |
    window.REACT_APP_ENVIRONMENT='DEV'
    window.API_GATEWAY='http://localhost:8086'
    window.API_ACC_GATEWAY = "https://now-apigwacc.lefebvre.es";

