variables:
    registryEndpoint: lefebvre-docker
trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - src/ApiGateways/*
    - k8s-lef/helm/apigwacc/*
    - k8s-lef/helm/apigwlex/* 
    exclude:
    - src/ApiGateways/Mobile.Bff.Account/aggregator/*
    - src/ApiGateways/Web.Bff.Shopping/aggregator/*
jobs:
- template: ../buildimages.yaml
  parameters:
    services: weblexonapigw webaccountapigw
    registryEndpoint: $(registryEndpoint)
    helmfrom: $(Build.SourcesDirectory)/k8s-LEF/helm
    helmto: $(Build.ArtifactStagingDirectory)/k8s-LEF/helm    
-
